const SOURCES={cours:'https://www.brvm.org/fr/cours-actions/0',resume:'https://www.brvm.org/fr/resume',capitalisations:'https://www.brvm.org/fr/capitalisations/0',volumes:'https://www.brvm.org/fr/volumes/0'};
const timeout=async(p,ms)=>{let t;try{return await Promise.race([p,new Promise((_,rej)=>{t=setTimeout(()=>rej(new Error(`timeout after ${ms}ms`)),ms)})])}finally{clearTimeout(t)}};
const clean=s=>String(s??'').replace(/<[^>]*>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
function num(s){const x=clean(s).replace(/%/g,'').trim();if(!x||x==='-')return null;const y=x.includes(',')?x.replace(/\./g,'').replace(/,/g,'.'):x.replace(/\s/g,'');const n=Number(y);return Number.isFinite(n)?n:null}
function dateOf(s){const m=clean(s).match(/(?:Lundi|Mardi|Mercredi|Jeudi|Vendredi|Samedi|Dimanche|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday),?\s+(\d{1,2})\s+(janvier|février|mars|avril|mai|juin|juillet|août|septembre|octobre|novembre|décembre|January|February|March|April|May|June|July|August|September|October|November|December),?\s+(\d{4})/i);if(!m)return null;const mo={janvier:'01',février:'02',mars:'03',avril:'04',mai:'05',juin:'06',juillet:'07',août:'08',septembre:'09',octobre:'10',novembre:'11',décembre:'12',january:'01',february:'02',march:'03',april:'04',may:'05',june:'06',july:'07',august:'08',september:'09',october:'10',november:'11',december:'12'};return `${m[3]}-${mo[m[2].toLowerCase()]}-${String(m[1]).padStart(2,'0')}`}
async function html(url){const r=await timeout(fetch(url,{headers:{'User-Agent':'Mozilla/5.0 TheCapitalInvest scraper'}}),25000);if(!r.ok)throw new Error(`${url} HTTP ${r.status}`);return r.text()}
function rows(h){const a=[];for(const m of h.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const c=[...m[1].matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(x=>clean(x[1]));if(c.length>=2)a.push(c)}return a}
function ticker(r){for(let i=0;i<r.length;i++){const t=r[i].trim().toUpperCase();if(/^[A-Z0-9]{3,6}$/.test(t)&&!['CODE','SYMBOL','TICKER','TOTAL','TOUS'].includes(t))return{i,t}}return null}
function nums(c){return c.filter(x=>/^[-+]?\s*\d[\d\s.,]*%?$/.test(x.trim())).map(num)}
function courses(h,d){const out=[];for(const r of rows(h)){const f=ticker(r);if(!f)continue;const n=nums(r.slice(f.i+1));if(n.length<4)continue;const [volume,prev,open,close,variation]=n;if(close==null)continue;out.push({ticker:f.t,date_seance:d,cours:close,cloture:close,ouverture:open,plus_haut:null,plus_bas:null,variation,variation_pct:variation,volume:volume==null?null:Math.round(volume),valeur_transigee:null,transactions:null,capitalisation:null})}return [...new Map(out.map(x=>[x.ticker,x])).values()]}
function volumes(h){const o={};for(const r of rows(h)){const f=ticker(r);if(!f)continue;const n=nums(r.slice(f.i+1));if(n.length>=2)o[f.t]={volume:n[0]==null?null:Math.round(n[0]),valeur_transigee:n[1]}}return o}
function caps(h){const o={};for(const r of rows(h)){const f=ticker(r);if(!f)continue;const n=nums(r.slice(f.i+1));if(n.length>=4)o[f.t]={capitalisation:n[3]}}return o}
function indices(h,d){const t=clean(h);const defs=[[/BRVM[- ]C(?:OMPOSITE)?\s+([\d\s.,]+)\s+([+-]?[\d.,]+)%/i,'BRVM-COMPOSITE'],[/BRVM[- ]30\s+([\d\s.,]+)\s+([+-]?[\d.,]+)%/i,'BRVM-30'],[/BRVM[- ]PRES(?:TIGE)?\s+([\d\s.,]+)\s+([+-]?[\d.,]+)%/i,'BRVM-PRESTIGE']];return defs.flatMap(([re,k])=>{const m=t.match(re);if(!m)return[];const v=num(m[1]),x=num(m[2]);return v==null?[]:[{indice:k,date_seance:d,valeur:v,variation:x,variation_pct:x}]})}
async function scrapeBrvm(){const now=new Date();const [ch,rh,caph,vh]=await Promise.all([html(SOURCES.cours),html(SOURCES.resume),html(SOURCES.capitalisations),html(SOURCES.volumes)]);const d=dateOf(ch)||dateOf(rh)||now.toISOString().slice(0,10);const c=courses(ch,d),v=volumes(vh),cap=caps(caph);for(const x of c){if(v[x.ticker])Object.assign(x,v[x.ticker]);if(cap[x.ticker])x.capitalisation=cap[x.ticker]}const idx=indices(rh,d).length?indices(rh,d):indices(ch,d);if(!c.length)throw new Error('Aucune cotation BRVM exploitable');return{date_seance:d,rows:c,indices:idx,source:'BRVM',count:c.length,sources:SOURCES,source_status:{cours:true,resume:true,capitalisations:true,volumes:true}}}
export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization, X-Requested-With');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({success:false,error:'Method not allowed'});try{return res.status(200).json({success:true,...await scrapeBrvm()})}catch(e){return res.status(502).json({success:false,error:'BRVM indisponible ou données non lisibles',details:String(e)})}}
